packaging_format = 2

id = "jellyseerr"
name = "Jellyseerr"
description.en = "Media request management and discovery tool for Jellyfin, Radarr, and Sonarr"
description.fr = "Outil de gestion de demandes et de découverte de médias pour Jellyfin, Radarr, et Sonarr"

version = "1.6.0~ynh2"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
code = "https://github.com/Fallenbagel/jellyseerr"

[integration]
yunohost = ">= 11.1.18"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"

  [resources]
   
    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/Fallenbagel/jellyseerr/archive/refs/tags/v1.6.0.tar.gz"
        sha256 = "f51014752e679d558c5c0ba6e3df363a1ef6c16b8a5176dbc0a4d3f3301ef156"
        autoupdate.strategy = "latest_github_tag"


    [resources.system_user]

    [resources.install_dir]
    
    [resources.data_dir]
   
    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5055
